apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.storage.persistentVolumeClaimName }}
spec:
  resources:
    requests:
      storage: 250M
  accessModes:
    - ReadWriteOnce
  storageClassName: default
