apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.service.name }}
spec:
  selector:
    {{- toYaml .Values.database.labels | nindent 4}}
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: 3306
    protocol: TCP
