name: Build and Deploy to AKS

on:
  push:
    branches:
      - master

jobs:
  build-and-push-docker:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
       name: Checkout source code
     - name: Log in to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
     - name: Build and push Docker image
       uses: docker/build-push-action@v5
       with:
         context: .
         file: ./Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/my_php_app:latest

  deploy-to-aks:
   needs: build-and-push-docker
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Set up Kubectl
       uses: azure/setup-kubectl@v3
     - name: Set up Helm
       uses: azure/setup-helm@v3
     - name: Decode AKS credentials
       run: echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
     - name: Helm Upgrade and Deploy
       run: helm upgrade --install ecomsite ./ecomsite-chart --set image.repository=bishal2469/my_php_app,image.tag=latest
         